# GAN and Window Configuration
GAN_INPUT_SIZE = 64
NATIVE_SCALING_FACTOR = 5.306
WINDOW_SIZES = [32, 48, 64]
WINDOW_STEP = 8

# Proposal Filtering
MIN_IMPORTANCE_SCORE = 0.25
MAX_REGIONS_PER_IMAGE = 15
MAX_OVERLAP_THRESHOLD = 0.5
SEMANTIC_DIFF_THRESHOLD = 0.15

# Optimization
HILL_CLIMB_STEPS = 2
HILL_CLIMB_STEP_SIZE = 2
EDGE_PENALTY_WEIGHT = 0.3

# Diversity
DIVERSITY_BUCKETS = 3
SAMPLES_PER_BUCKET = 3

# Normalization & Quality
MIN_VALID_SCORE_THRESHOLD = 0.20
REJECT_EMPTY_THRESHOLD = 0.05

# Paths
DATASET_DIR = "output/dataset"
DEBUG_DIR = "output/debug_preprocessing"
