# GAN Hyperparameters
GAN_INPUT_SIZE = 128
GAN_LATENT_DIM = 100         # nz
GAN_GENERATOR_FILTERS = 64   # ngf
GAN_DISCRIMINATOR_FILTERS = 64 # ndf
GAN_CHANNELS = 3             # nc
GAN_BATCH_SIZE = 64
GAN_NUM_EPOCHS = 350
GAN_LEARNING_RATE = 0.0002
GAN_BETA1 = 0.5
GAN_N_CRITIC = 1
GAN_WORKERS = 0
